[package]
name = "nekojni"
version = "0.1.0"
authors = ["Lymia Aluysia <lymia@lymia.moe>"]
edition = "2021"

[dependencies]
bytemuck = "1.8.0"
jni = "0.19"
parking_lot = { version = "0.12.0", features = ["nightly"] }
thiserror = "1.0.30"

nekojni_macros = { version = "0.1.0", path = "nekojni_macros" }
nekojni_signatures = { version = "0.1.0", path = "nekojni_signatures" }

[workspace]
members = ["nekojni_macros", "nekojni_signatures"]
