WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

ident = @{ ident_start ~ ident_char* }
ident_start = @{ 'a'..'z' | 'A'..'Z' | "$" | "_" }
ident_char = @{ 'a'..'z' | 'A'..'Z' | '0'..'9' | "$" | "_" }

ty = { path ~ ty_array_braces* }
ty_array_braces = { "[" ~ "]" }

sig = { "(" ~ sig_param_list? ~ ")" ~ ("->" ~ ty)? }
sig_param_list = { ty ~ ("," ~ ty)* }

path = { ident ~ ("." ~ ident)* }

full_sig = { SOI ~ sig ~ EOI }
full_ty = { SOI ~ ty ~ EOI }
full_path = { SOI ~ path ~ EOI }
