ident = @{ ident_char+ }
ident_char = @{ ' '..'-' | '0'..':' | "=" | '?'..'Z' | '\\'..'~' }

ty = { ty_array_head* ~ (ty_prim | ty_class) }
ty_prim = { "Z" | "B" | "C" | "S" | "I" | "J" | "F" | "D" | "V" }
ty_class = { "L" ~ path ~ ";" }
ty_array_head = { "[" }

sig = { "(" ~ ty* ~ ")" ~ ty }

path = { ident ~ ("/" ~ ident)* }

full_sig = { SOI ~ sig ~ EOI }
full_ty = { SOI ~ ty ~ EOI }
full_path = { SOI ~ path ~ EOI }
