[package]
name = "nekojni_macros"
version = "0.1.0"
authors = ["Lymia Aluysia <lymia@lymia.moe>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"

nekojni_signatures = { version = "0.1.0", path = "../nekojni_signatures" }
